"use client"

import { useState } from "react"
import { Check, Copy, Code } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter'
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism'

export function TypeViewer({ tsCode }: { tsCode: string }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(tsCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (!tsCode) return null

  return (
    <Dialog>
      <DialogTrigger className="inline-flex items-center justify-center whitespace-nowrap text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-9 rounded-md px-3 gap-2">
        <Code className="h-4 w-4" />
        View Types
      </DialogTrigger>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle>Generated TypeScript Interface</DialogTitle>
          <DialogDescription>
            These types were automatically generated by Gemini based on the current payload schema.
          </DialogDescription>
        </DialogHeader>
        <div className="relative mt-4">
          <Button
            size="icon"
            variant="ghost"
            className="absolute top-2 right-2 z-10 text-slate-300 hover:text-white hover:bg-slate-700"
            onClick={handleCopy}
          >
            {copied ? <Check className="h-4 w-4 text-green-400" /> : <Copy className="h-4 w-4" />}
          </Button>
          <ScrollArea className="h-[400px] w-full rounded-md border bg-[#1E1E1E]">
            <SyntaxHighlighter
              language="typescript"
              style={vscDarkPlus}
              customStyle={{ margin: 0, padding: '1.5rem', background: 'transparent' }}
            >
              {tsCode}
            </SyntaxHighlighter>
          </ScrollArea>
        </div>
      </DialogContent>
    </Dialog>
  )
}
